// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAES52iP-9auSRx6KRPUFRHhS8yXkF_EXs',
    appId: '1:305647422127:android:5c9d548bc9d7f03829225a',
    messagingSenderId: '305647422127',
    projectId: 'gapi-b0d34',
    databaseURL: 'https://gapi-b0d34-default-rtdb.firebaseio.com',
    storageBucket: 'gapi-b0d34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt5kYQjgp5Un61JxRfMSvpysGOsbkk9ps',
    appId: '1:305647422127:ios:6865b4ff1ced1a3b29225a',
    messagingSenderId: '305647422127',
    projectId: 'gapi-b0d34',
    databaseURL: 'https://gapi-b0d34-default-rtdb.firebaseio.com',
    storageBucket: 'gapi-b0d34.appspot.com',
    iosClientId: '305647422127-p70kjbom7vmtk9no351pbdugb7o31qkc.apps.googleusercontent.com',
    iosBundleId: 'com.example.gapi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt5kYQjgp5Un61JxRfMSvpysGOsbkk9ps',
    appId: '1:305647422127:ios:6865b4ff1ced1a3b29225a',
    messagingSenderId: '305647422127',
    projectId: 'gapi-b0d34',
    databaseURL: 'https://gapi-b0d34-default-rtdb.firebaseio.com',
    storageBucket: 'gapi-b0d34.appspot.com',
    iosClientId: '305647422127-p70kjbom7vmtk9no351pbdugb7o31qkc.apps.googleusercontent.com',
    iosBundleId: 'com.example.gapi',
  );
}
